steps:
  # Paso 0: Maven con Java 21
  - name: "maven:3.9-eclipse-temurin-21"
    entrypoint: "mvn"
    args: [ "clean", "install", "-DskipTests" ]

  # Paso 1: Build de Docker apuntando al nuevo repo
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/todo-494622/todo-repo/todo-app",
        ".",
      ]

options:
  logging: CLOUD_LOGGING_ONLY

# Cambia esto también para que coincida
images:
  - "us-central1-docker.pkg.dev/todo-494622/todo-repo/todo-app"